CREATE TABLE history (
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  place VARCHAR(100) NULL,
  emergency VARCHAR(100) NULL,
  need VARCHAR(100) NULL,
  message VARCHAR(200) NULL,
  node INT(11) NOT NULL
);

ALTER TABLE history
  MODIFY place TEXT;