CREATE TABLE history (
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  place VARCHAR(100) NULL,
  emergency VARCHAR(100) NULL,
  need VARCHAR(100) NULL,
  message VARCHAR(100) NULL,
  node INT(11) NOT NULL
  cookies VARCHAR(100) NOT NULL
);
